FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN python scripts/train_model.py
CMD ["sh", "-c", "python scripts/wait_for_services.py && gunicorn -b 0.0.0.0:5000 run:app"]
